export const DRAWER_WITH = 240;

export const LOGO_URL = '/images/logo.svg';

export const ADMIN_OPTIONS = [
  'REALIZAR PEDIDO',
  'RESERVAR MESA',
  'GENERAR CUENTA',
  'RESERVAS / ASIGNAR',
  'VISUALIZAR ORDENES',
  'GENERAR CUADRE',
  'EDITAR INVENTARIO',
  'EDITAR CATEGORIA',
  'EDITAR MESAS',
  'GESTIONAR USUARIOS',
  'GESTIONAR MENU',
];
